apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: repo-1
  template:
    metadata:
      labels:
        app: repo-1
    spec:
      containers:
      - name: repo-1
        image: abhishekmaniyar3811/node-1-prod:15
        ports:
        - containerPort: 3000

