apiVersion: v1
kind: Service
metadata:
  name: repo-1-dev-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: repo-1-dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
