apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repo-1-dev-app
  namespace: argocd
spec:
  project: repo-1-dev
  source:
    repoURL: 'https://github.com/abhishekmaniy/node-1.git'
    targetRevision: develop
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
