apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: repo-1-main
  namespace: argocd
spec:
  description: "Project for the main branch of repo-1"
  sourceRepos:
  - 'https://github.com/abhishekmaniy/node-1.git'
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
