apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: repo-1-dev
  namespace: argocd
spec:
  description: "Project for the dev branch of repo-1"
  sourceRepos:
  - 'https://github.com/your-repo/your-project.git'
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
