apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: prod-role
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-role-binding
  namespace: default
subjects:
- kind: User
  name: prod-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prod-role
  apiGroup: rbac.authorization.k8s.io
